logging:
  level:
    root: INFO
    com.dist.sys: INFO

spring:
  jmx:
    enabled: false
  redis:
    host: localhost
    port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Zagreb
    serialization:
      fail-on-empty-beans: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus